### ISSUE TITLE
Not working with nvm

### ISSUE THREAD

**Issue by SplittyDev** [johnvicinno/CoderKit#1]
Hi, I use node version manager (nvm) to manage my NodeJS versions, and this doesn't seem to work with CoderKit.

I am aware that CoderKit specifically states to make sure that `node` is not a shim, but with nvm, it kind of has to be a shim. I would've expected to be able to set the node path in the settings somewhere to make it work, but there doesn't seem to be an option to do so.

I propose adding an option to override the `node` path. Installing node the conventional way isn't really an option for me, because that would mess with `nvm`.

**Comment by johnvicinno** [comment]
Thanks for letting us know. We are looking into it now and will see if we can solve it quickly. will keep you posted here.

**Comment by johnvicinno** [comment]
just released 1.0.2 with Node path setting option. Can you please try to see if it fixes your issue? We don't have nvm environment and cannot test the fix.  Let me know if it works. Thanks.

**Comment by SplittyDev** [comment]
Thanks for the new version! Something in that version definitely fixed the issue for me, without even having to set the node path manually. Before, I was getting errors when trying to run the LSP, but now it just works, without any changes.

Did you perhaps add the `/usr/bin/env`-based node discovery in that version too? I only remember the shell-based execution environments before. Not sure if that's exactly what fixed it, all I can say is that it works now.

I've also tested it with setting the node path manually: This works perfectly too.

In case anyone wants to know how to obtain the true node executable path from `nvm`:
Run `nvm which node` to get the full path to the current node version.

On macOS, run `nvm which node | tr -d '\n' | pbcopy` to get the node path directly in your pasteboard.
